# docker-compose.yaml
version: "3.8"

services:
  rfes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rfes
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      # Монтируем только логи, файлы сайта уже в образе
      - ./logs:/var/log/nginx
    networks:
      - rfes-net

networks:
  rfes-net:
    driver: bridge